### ISSUE TITLE
URIs duplicate

### ISSUE THREAD

**Issue by xmolero** [ALIADA/aliada-tool#115] opened 2015-06-17 10:20 UTC
First of all, I see that the authors are duplicates and the rdfizer is unfiltered
Secondly, the URIs created is the same for different authors. Why?

![authors](https://cloud.githubusercontent.com/assets/10447860/8204761/2921ecc8-14eb-11e5-96ce-072cccd65b77.JPG)

**Comment by agazzarini** [comment] 2015-06-17 10:26
@xmolero this is what the GUI is doing...I cannot say what you did there

"rdfizer is unfiltered" what does it mean? What does the screenshot have to do with the RDFizer?

AG

**Comment by agazzarini** [comment] 2015-06-17 10:31
Hi @xmolero to be more precise: it would be good, when you fill a bug, assigning or citing someone who is supposed to be in charge  / (at least answer) about that, otherwise it won't be clear for who is the question.

AG

**Comment by xmolero** [comment] 2015-06-17 10:58
@agazzarini excuse me! The issue is for you. I say that the rdfizer does wrong the URIs and duplicates the authors. The screenshots is a simple query to show the authors.

**Comment by agazzarini** [comment] 2015-06-17 11:37
Send me an email (attachments here I think aren't allowed) with the dataset you've converted. The duplication couldn't be an issue, as the entity detection mainly reasons on fields/subfields equality

**Comment by agazzarini** [comment] 2015-06-21 10:16
I also need the query you're doing in that page

**Comment by xmolero** [comment] 2015-06-22 07:21
The queries are in this file: https://github.com/ALIADA/aliada-tool/blob/master/aliada/aliada-shared-module/src/main/java/eu/aliada/shared/rdfstore/RDFStoreDAO.java 
Here, you have the authors, the objects, the manifestations and the works queries, but if you only need the query that I did in that page is getAuthors method.

**Comment by idoiamurua** [comment] 2015-06-22 07:25
The query of the authors for graph `<http://data.artium.org/id/collections/library/bib>` in SPARQL endpoint `http://aliada.scanbit.net:8891/sparql` would be:

```
 PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
		PREFIX ecrm:   <http://erlangen-crm.org/current/>
		PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
		SELECT DISTINCT ?res ?name FROM <http://data.artium.org/id/collections/library/bib> 
		WHERE { {{?res rdf:type ecrm:E39_Actor}
		UNION {?res rdf:type ecrm:E21_Person}
		UNION {?res rdf:type efrbroo:F10_Person}}
		 . ?res ecrm:P131_is_identified_by ?apel
		 . ?apel ecrm:P3_has_note ?name }
		 ORDER BY ?res ?name
```

**Comment by agazzarini** [comment] 2015-06-22 08:18
Ok, thanks. So now I need the dataset (if that is not huuge, otherwise a small subset containing those authors) you've inserted. I mean, data that you're querying where there are those (duplicated) authors

**Comment by idoiamurua** [comment] 2015-06-22 10:18
I have just uploadad the "resultSumaryList.xml" file Xabier sent by e-mail to the `<http://data.artium.org/id/collections/library/bib>` graph in SPARQL endpoint `http://aliada.scanbit.net:8891/sparql`.

**Comment by idoiamurua** [comment] 2015-06-22 10:22
Use the following query instead:

```
 PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
		PREFIX ecrm:   <http://erlangen-crm.org/current/>
		PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
		SELECT DISTINCT ?res ?name FROM <http://data.artium.org/id/collections/library/bib> 
		WHERE { {{?res rdf:type ecrm:E39_Actor}
		UNION {?res rdf:type ecrm:E21_Person}
		UNION {?res rdf:type efrbroo:F10_Person}}
		 . ?res ecrm:P131_is_identified_by ?apel
		 . ?apel ecrm:P3_has_note ?name }
		 ORDER BY ?name
```

**Comment by agazzarini** [comment] 2015-06-22 17:56
Hi @idoiamurua, does the resultSumaryList.xml contains marc records? If so, could you please send me that file? I cannot reproduce this bug so sharing the same data would be useful

**Comment by idoiamurua** [comment] 2015-06-24 08:05
@agazzarini 

I have tried again with the same imported MARC BIB file (I have compiled and deployed the new WAR), and two different persons/authors continue appearing with the same URI. See the two selected links in the attached image:

![image](https://cloud.githubusercontent.com/assets/7601333/8325272/5940760a-1a58-11e5-93ea-cf33a1631bde.png)

**Comment by idoiamurua** [comment] 2015-06-24 08:09
Doing a query in the SPARQL endpoint, the repeated URI-s are seen better as I have ordered by URI. See attached figure:
![image](https://cloud.githubusercontent.com/assets/7601333/8325330/097d024a-1a59-11e5-82db-1f35c5d13e3e.png)

**Comment by agazzarini** [comment] 2015-06-24 08:14
Hi @idoiamurua did you clean the dataset?

**Comment by idoiamurua** [comment] 2015-06-24 08:20
Yes I did. I have tried it again just in case and I get the same result.

**Comment by agazzarini** [comment] 2015-06-24 15:13
I'm not able to reproduce the error...each diffenent person gets a different URI in my server 

--------------------------------

In addition, I corrected some minor things like the same name with different URIs. This is a really "hairy" stuff, as the label you see in the screenshot couldn0t be the only information that we used to built the URI. So for example, if you have 

$aJohn Mess$d1888-

and 

$aJon Mess$d1888-1912

In the user interface you will see 2 John Mess with different URIs

**Comment by idoiamurua** [comment] 2015-06-25 07:26
Do you think the machine configuration can affect the URI generation?
I have tried it again at aliada.scanbit.net (cleared the graph, uploaded the last built RDFizer WAR, restart tomcat) and it continues generating the same URIs for different actor/names.
I do not understand what it is happenning.

Regarding the issue that diferent actor resources with the same name have different URIs, I understand it is difficult to avoid, as the actor names cannot be considered identifiers.

**Comment by idoiamurua** [comment] 2015-06-25 07:33
I attach an image:

![image](https://cloud.githubusercontent.com/assets/7601333/8349455/36472d72-1b1d-11e5-892f-cfbd9a5c8e8b.png)

**Comment by agazzarini** [comment] 2015-06-25 19:28
Theoretically no, as I have the same URIs in my machine (without duplicates)

The UUID function we're using generates a UUID from a given string and starting from the same value you will always get the same result...so that sounds really strange

There should be aomething that happens when the RDFizer processes a lot of records. I tried with a small subset, after isolating those recorda that produce duplicated entries, as it's very hard to understand what is happening with thousand records.

In this context I am almost sure the uuid function ia working properly so maybe I'm looking in the wrong direction..some concurrency issue, I don't know

**Comment by idoiamurua** [comment] 2015-06-26 06:58
Did you try that small subset in aliada.scanbit.net machine?
If not, Could you send to me that subset and I make that try?

**Comment by agazzarini** [comment] 2015-06-26 08:14
That has nothing to do with the dataset size, or the concurrency. I just tried with the whole dataset, putting a stupid map that remembers each headings => generated URI and another stupid "if" block that prints our a message when a duplicated id (with a different heading) is detected....nothing is printed out :(

**Comment by agazzarini** [comment] 2015-06-26 08:45
I just committed a dummy version of ALIADA that prints out only authors and their appellations. Trying into Aliada server...

**Comment by idoiamurua** [comment] 2015-06-26 08:49
Are you trying it or do you want me to try it?
Xabier is making changes in aliada.scanbit.net server, so you better wait till Xabier tells you.

**Comment by agazzarini** [comment] 2015-06-26 08:56
Ah ok, sorry I didn't see your post...I'm just trying

**Comment by agazzarini** [comment] 2015-06-26 09:16
Ok, I ran the RDFizer directly from the command line. It seems there are no duplicates

http://aliada.scanbit.net:8891/sparql-auth?default-graph-uri=http%3A%2F%2Fdata.artium.org%2Fid%2Fcollections%2Flibrary%2Fbib&query=+PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0A++++++++PREFIX+ecrm%3A+++%3Chttp%3A%2F%2Ferlangen-crm.org%2Fcurrent%2F%3E%0D%0A++++++++PREFIX+efrbroo%3A+%3Chttp%3A%2F%2Ferlangen-crm.org%2Fefrbroo%2F%3E%0D%0A++++++++SELECT+DISTINCT+%3Fres+%3Fname+FROM+%3Chttp%3A%2F%2Fdata.artium.org%2Fid%2Fcollections%2Flibrary%2Fbib%3E+%0D%0A++++++++WHERE+{+{{%3Fres+rdf%3Atype+ecrm%3AE39_Actor}%0D%0A++++++++UNION+{%3Fres+rdf%3Atype+ecrm%3AE21_Person}%0D%0A++++++++UNION+{%3Fres+rdf%3Atype+efrbroo%3AF10_Person}}%0D%0A+++++++++.+%3Fres+ecrm%3AP131_is_identified_by+%3Fapel%0D%0A+++++++++.+%3Fapel+ecrm%3AP3_has_note+%3Fname+}%0D%0A+++++++++ORDER+BY+%3Fres&format=text%2Fhtml&timeout=0&debug=on

**Comment by agazzarini** [comment] 2015-06-26 09:16
So, @xmolero or @idoiamurua : could you please run the whole process starting from the user interface?

**Comment by agazzarini** [comment] 2015-06-26 09:16
Please do a manual clean of the graph before doing that

**Comment by agazzarini** [comment] 2015-06-26 09:19
A little correction: it seems we have some duplicate but only for those headings that result in the same string before being processed by the UUID processor ("Fenosa, Apelles", "Fenosa, Apel les") but this is another thing from this issue

**Comment by agazzarini** [comment] 2015-06-26 09:26
Sorry again: that duplicate is right, the system detected that it is the same person

**Comment by agazzarini** [comment] 2015-06-26 09:40
@idoiamurua @xmolero I just replaced the dummy (MARC) conversion template with the full version. Now all triples are printed out and, running the RDFizer from the command line:

```
> cp /work/data/aliada/marcxml/.done/marc_bib1435305034374.xml.1 /usr/share/tomcat/upload/marc_bib1435305034374.xml

curl -X PUT "http://127.0.0.1:8080/aliada-rdfizer-2.0/jobs/1"
> 
```

I see no duplicates, so I'm closing the issue.

**Closed by agazzarini** 2015-06-26 09:40 UTC
Labels: bug

**Comment by idoiamurua** [comment] 2015-06-26 11:07
I have just ran the RDFizer from the user interface and now it seems it does not generate any duplicates. 
What did you change?

**Comment by agazzarini** [comment] 2015-06-26 11:51
I added a further clean up of the velocity context associated to each (converted) record. I actually didn't get how that can influence the duplication but in some way, it did

**Comment by idoiamurua** [comment] 2015-06-26 11:53
OK. So you deployed the last WAR of the RDFizer to aliada.scanbit.net machine. Didn´t you?

**Comment by agazzarini** [comment] 2015-06-26 11:54
yes

**Comment by idoiamurua** [comment] 2015-06-26 11:54
OK.

**Comment by idoiamurua** [comment] 2015-06-29 11:55
@agazzarini 
The RDFizer WAR you deployed to Scanbit machine works perfectly, but I have downloaded from Github the lastest changes of the RDFizer, generated the WAR and deployed it to Artium´s machine and when importing MARC BIB and MARC AUTH records, the RDFizer doe not finish and the "infrastructure.log" file contains the following error:

```
2015-06-29 13:37:16,196 ERROR Failed delivery for (MessageId: ID-aliada-artium-scanbit-35195-1435577192588-0-227 on ExchangeId: ID-aliada-artium-scanbit-35195-1435577192588-0-253). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[almodovar1435577831967.xml.51]

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[route14           ] [route14           ] [seda://marcxml-record-channel?blockWhenFull=true&concurrentConsumers=5&size=10] [       112]
[route6            ] [to8               ] [seda:marcxml-record-channel?concurrentConsumers=5&size=1000&blockWhenFull=true] [         0]
[route14           ] [process34         ] [ref:string-to-xml                                                             ] [         8]
[route14           ] [process35         ] [ref:detect-frbr-entities                                                      ] [         9]

Exchange
---------------------------------------------------------------------------------------------------------------------------------------
Exchange[
        Id                  ID-aliada-artium-scanbit-35195-1435577192588-0-253
        ExchangePattern     InOnly
        Headers             {breadcrumbId=ID-aliada-artium-scanbit-35195-1435577192588-0-227, CamelFileAbsolute=true, CamelFileAbsolutePath=/work/data/aliada/marcxml/.working/almodovar1435577831967.xml.51, CamelFileLastModified=1435577831000, CamelFileLength=55577, CamelFileName=almodovar1435577831967.xml.51, CamelFileNameConsumed=almodovar1435577831967.xml.51, CamelFileNameOnly=almodovar1435577831967.xml.51, CamelFileParent=/work/data/aliada/marcxml/.working, CamelFilePath=/work/data/aliada/marcxml/.working/almodovar1435577831967.xml.51, CamelFileRelativePath=/work/data/aliada/marcxml/.working/almodovar1435577831967.xml.51, CamelRedelivered=false, CamelRedeliveryCounter=0, format=marcxml, jobId=51}
        BodyType            org.apache.xerces.dom.DeferredDocumentImpl
        Body                <marc:record><marc:leader>02237ngm a2200301   4500</marc:leader><marc:controlfield tag="001">000000083503</marc:controlfield><marc:controlfield tag="003">CaOOAMICUS</marc:controlfield><marc:controlfield tag="005">20070301180840.0</marc:controlfield><marc:controlfield tag="007">vd czaizn</marc:controlfield><marc:controlfield tag="008">040608s2002    sp                znspa u</marc:controlfield><marc:datafield ind1=" " ind2=" " tag="040"><marc:subfield code="a">BCD</marc:subfield><marc:subfield code="b">spa</marc:subfield></marc:datafield><marc:datafield ind1="0" ind2=" " tag="130"><marc:subfield code="a">Hable con ella.</marc:subfield></marc:datafield><marc:datafield ind1="0" ind2="0" tag="245"><marc:subfield code="a">Hable con ella</marc:subfield><marc:subfield code="h">[Vídeo] /</marc:subfield><marc:subfield code="c">un film de Pedro Almodovar.</marc:subfield></marc:datafield><marc:datafield ind1=" " ind2=" " tag="260"><marc:subfield code="a">[Barcelona] :</marc:subfield><marc:subfield code="b">El Deseo,</marc:subfield><marc:subfield code="c">D.L. 2002.</marc:subfield></marc:datafield><marc:datafield ind1=" " ind2=" " tag="300"><marc:subfield code="a">1 videodisco (DVD) (ca. 109 min.) :</marc:subfield><marc:subfield code="b">son., col.</marc:subfield></marc:datafield><marc:datafield ind1=" " ind2=" " tag="508"><marc:subfield code="a">Guión: Pedro Almodóvar ; fotografía: Javier Aguirresarobe ; música: Alberto Iglesias ; montaje: José Salcedo ; producción: Esther García ; dirección artística: Antxón Gómez ; vestuario: Sonia Grande.</marc:subfield></marc:datafield><marc:datafield ind1="0" ind2=" " tag="511"><marc:subfield code="a">Intérpretes: Javier Cámara, Leonor Watling, Darío Grandinetti, Rosario Flores, con la participación de Geraldine Chaplin, Adolfo Fernández, Chus Lampreave, Fele Martínez, Marisa Paredes, Paz Vega</marc:subfield></marc:datafield><marc:datafield ind1=" " ind2=" " tag="520"><marc:subfield code="a">"Hable con ella" es una historia sobre la amistad de dos hombres, sobre la soledad, y la larga convalecencia de las heridas provocadas por la pasión. Es también una película sobre la incomunicación de las parejas y sobre la comunicación. Sobre el cine como tema de conversación. Sobre cómo los monólogos ante una persona silente pueden ser una forma eficaz de diálogo. Del silencio como elocuencia del cuerpo, del cine como vehículo ideal en las relaciones de las personas, de como el cine contado en palabras detiene el tiempo y se instala en las vida de quien lo cuenta y del que lo escucha. "Hable con ella" es una película sobre la alegría de narrar y sobre la palabra como arma para huir de la soledad, la enfermedad, la muerte y la locura.</marc:subfield></marc:datafield><marc:datafield ind1=" " ind2=" " tag="521"><marc:subfield code="a">No recomendada para menores de 13 años</marc:subfield></marc:datafield><marc:datafield ind1=" " ind2=" " tag="545"><marc:subfield code="a">España, 2002</marc:subfield></marc:datafield><marc:datafield ind1=" " ind2=" " tag="546"><marc:subfield code="a">Idiomas: castellano ; subtítulos: castellano para sordos</marc:subfield></marc:datafield><marc:datafield ind1="1" ind2=" " tag="590"><marc:subfield code="a">BCD4</marc:subfield></marc:datafield><marc:datafield ind1=" " ind2="4" tag="650"><marc:subfield code="a">Drama</marc:subfield><marc:subfield code="v">Películas cinematográficas.</marc:subfield></marc:datafield><marc:datafield ind1=" " ind2="4" tag="650"><marc:subfield code="a">Cine</marc:subfield><marc:subfield code="z">España</marc:subfield><marc:subfield code="y">2001-2010</marc:subfield><marc:subfield code="v">Películas cinematográficas.</marc:subfield></marc:datafield><marc:datafield ind1="1" ind2=" " tag="700"><marc:subfield code="a">Almodóvar, Pedro,</marc:subfield><marc:subfield code="d">1949- .</marc:subfield></marc:datafield><marc:datafield ind1="0" ind2=" " tag="787"><marc:subfield code="t">Hable con ella.</marc:subfield><marc:subfield code="k">Zinemaren inguruan (Artium. Biblioteca)</marc:subfield><marc:subfield code="k">En torno al cine (Artium. Biblioteca)</marc:subfield><marc:subfield code="w">(BCD)105655</marc:subfield></marc:datafield><marc:datafield ind1=" " ind2=" " tag="850"><marc:subfield code="a">ARTP</marc:subfield></marc:datafield><marc:datafield ind1=" " ind2=" " tag="852"><marc:subfield code="a">ARTP</marc:subfield><marc:subfield code="x">****</marc:subfield><marc:subfield code="m">DVD ALM-PE 5</marc:subfield><marc:subfield code="q">COMPRA</marc:subfield><marc:subfield code="A">1   G73@  </marc:subfield><marc:subfield code="B">21378</marc:subfield><marc:subfield code="F">19411         </marc:subfield><marc:subfield code="S">DVD ALM-PE 5</marc:subfield></marc:datafield></marc:record>
]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[almodovar1435577831967.xml.51]
        at org.apache.camel.util.ObjectHelper.wrapCamelExecutionException(ObjectHelper.java:1379)
        at org.apache.camel.impl.DefaultExchange.setException(DefaultExchange.java:283)
        at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:66)
        at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72)
        at org.apache.camel.processor.interceptor.TraceInterceptor.process(TraceInterceptor.java:163)
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
        at org.apache.camel.component.seda.SedaConsumer.sendToConsumers(SedaConsumer.java:291)
        at org.apache.camel.component.seda.SedaConsumer.doRun(SedaConsumer.java:200)
        at org.apache.camel.component.seda.SedaConsumer.run(SedaConsumer.java:147)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: eu.aliada.shared.Strings.clean(Ljava/lang/String;)Ljava/lang/String;
        at eu.aliada.rdfizer.pipeline.format.marc.selector.FirstMatch.evaluate(FirstMatch.java:33)
        at eu.aliada.rdfizer.pipeline.format.marc.frbr.WorkDetector.detect(WorkDetector.java:54)
        at eu.aliada.rdfizer.pipeline.format.marc.frbr.FrbrEntitiesDetector.frbrDetection(FrbrEntitiesDetector.java:106)
        at eu.aliada.rdfizer.pipeline.format.marc.frbr.FrbrEntitiesDetector.process(FrbrEntitiesDetector.java:78)
        at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
        ... 13 more
```
Did you upload all the changes to Github?

**Comment by agazzarini** [comment] 2015-06-29 11:59
Yes, I think you didn't build the shared project

**Comment by idoiamurua** [comment] 2015-06-29 12:07
Yes. That is! Thank you!
